const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),ts=require('typescript');
require.extensions['.ts']=(m,f)=>m._compile(ts.transpileModule(fs.readFileSync(f,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText,f);
const kd=require('../src/lib/kinhdich.ts');
test('static trigram is The; Quan Mai example',()=>{const r=kd.castHexagram(2,3,2);assert.equal(r.movingPos,1);assert.equal(r.the.name,'Đoài');assert.equal(r.dung.name,'Ly');});
test('all coin patterns preserve six lines and all movers',()=>{for(let n=0;n<4096;n++){let v=n;const a=Array.from({length:6},()=>{const x=6+v%4;v=Math.floor(v/4);return x});const r=kd.castCoins(a);assert.deepEqual(r.lines.map(l=>l.bit),a.map(x=>x%2));assert.deepEqual(r.movingPositions,a.flatMap((x,i)=>x===6||x===9?[i+1]:[]));assert.deepEqual([...r.bienLower.bits,...r.bienUpper.bits],a.map(x=>x===6?1:x===9?0:x%2));assert.equal(r.method,'coins');}});
test('eight coin faces have 1:3:3:1 distribution',()=>{const counts={};for(let n=0;n<8;n++){const sum=kd.coinValue([n&1,(n>>1)&1,(n>>2)&1]);counts[sum]=(counts[sum]||0)+1;}assert.deepEqual(counts,{6:1,7:3,8:3,9:1});});
test('64 King Wen identities independent upper/lower matrix',()=>{const matrix=[[1,43,14,34,9,5,26,11],[10,58,38,54,61,60,41,19],[13,49,30,55,37,63,22,36],[25,17,21,51,42,3,27,24],[44,28,50,32,57,48,18,46],[6,47,64,40,59,29,4,7],[33,31,56,62,53,39,52,15],[12,45,35,16,20,8,23,2]];for(let l=1;l<=8;l++)for(let u=1;u<=8;u++)assert.equal(kd.hexagramInfo(kd.trigramByIdx(u),kd.trigramByIdx(l)).number,matrix[l-1][u-1]);assert.equal(kd.hexagramName(kd.trigramByIdx(6),kd.trigramByIdx(3)),'Thủy Hỏa Ký Tế');});
test('serial and phones preserve leading zeros and normalize safely',()=>{assert.equal(kd.normalizeDigits('serial','AB001234'),'001234');assert.equal(kd.normalizeDigits('phone','+84 912 345 678'),'0912345678');assert.equal(kd.normalizeDigits('phone','0084912345678'),'0912345678');assert.throws(()=>kd.normalizeDigits('serial','12AB34'));assert.throws(()=>kd.normalizeDigits('phone','123'));const r=kd.castDigits('serial','AB001234');assert.equal(r.upper.idx,1);assert.equal(r.lower.idx,1);assert.equal(r.movingPos,4);});
test('time respects Vietnamese civil midnight and lunar new year',()=>{const a=kd.castTime('2024-02-09T16:59:00Z'),b=kd.castTime('2024-02-09T17:00:00Z');assert.equal(a.metadata.lunarDay,30);assert.equal(b.metadata.lunarDay,1);assert.equal(b.metadata.lunarMonth,1);assert.equal(b.metadata.yearBranch,5);assert.equal(b.metadata.hourBranch,1);assert.throws(()=>kd.castTime('bad'));});
test('legacy replay retains original The and distinct history entries',()=>{const e={s1:1,s2:6,s3:6,question:'old',savedAt:1,name:'Trời Nước',movingPos:1};const r=kd.replayKdHistory(e);assert.equal(r.the.name,'Khảm');assert.equal(r.algorithmVersion,'legacy-v1');const modern=kd.castHexagram(1,6,6);const saved=kd.createKdHistory(modern,'new');assert.deepEqual(kd.replayKdHistory(saved),modern);assert.notEqual(kd.createKdHistory(modern,'a').id,kd.createKdHistory(modern,'b').id);});
test('coin DTO never exposes fabricated Mai Hoa fields; phone payload never exposes number',()=>{const c=kd.kdPromptData(kd.castCoins([6,7,8,9,6,9]));assert.equal(c.the,undefined);assert.equal(c.mutual,undefined);const p=kd.castDigits('phone','0912345678');assert.ok(!JSON.stringify(p).includes('0912345678'));assert.ok(!JSON.stringify(kd.kdPromptData(p)).includes('091'));});
test('time branch 23h rollover, leap month and formula modulo',()=>{const a=kd.castTime('2023-03-22T15:59:00Z'),b=kd.castTime('2023-03-22T16:00:00Z');assert.equal(a.metadata.leapMonth,true);assert.equal(a.metadata.lunarMonth,2);assert.equal(a.metadata.lunarDay,1);assert.equal(a.metadata.hourBranch,12);assert.equal(b.metadata.hourBranch,1);for(let h=0;h<24;h++){const r=kd.castTime(`2024-02-10T${String(h).padStart(2,'0')}:00:00+07:00`),m=r.metadata,total=m.yearBranch+m.lunarMonth+m.lunarDay;assert.equal(r.upper.idx,total%8||8);assert.equal(r.lower.idx,(total+m.hourBranch)%8||8);assert.equal(r.movingPos,(total+m.hourBranch)%6||6);}});
test('history keeps same-number distinct questions and removes only matching ID',()=>{const store=new Map();global.window={};global.localStorage={getItem:k=>store.get(k)||null,setItem:(k,v)=>store.set(k,v)};const r=kd.castHexagram(1,2,3),a=kd.createKdHistory(r,'a'),b=kd.createKdHistory(r,'b');a.savedAt=123;b.savedAt=123;kd.pushKdHistory(a);assert.equal(kd.pushKdHistory(b).length,2);assert.equal(kd.removeKdHistory(a.id)[0].id,b.id);delete global.window;delete global.localStorage;});
test('reject malformed coins and cache includes method and question',()=>{assert.throws(()=>kd.castCoins([6]));assert.throws(()=>kd.castCoins([6,7,8,9,6,10]));assert.throws(()=>kd.castCoins([6,6,6,6,6,6],Array(6).fill([1,1,1])));const a=kd.castDigits('digits','001234'),b=kd.castDigits('serial','AB001234');assert.notEqual(kd.kdCacheKey(a,'a'),kd.kdCacheKey(b,'a'));assert.notEqual(kd.kdCacheKey(a,'a'),kd.kdCacheKey(a,'b'));});
test('invalid stored records cannot reach rendering; valid legacy preserved',()=>{const store=new Map();global.window={};global.localStorage={getItem:k=>store.get(k)||null,setItem:(k,v)=>store.set(k,v)};store.set('astrox_kd_history_v1',JSON.stringify([null,{}, {question:'x',name:'bad',s1:1,s2:2,s3:3,savedAt:1,movingPos:1,snapshot:{}},{question:'valid',name:'old',s1:1,s2:2,s3:3,savedAt:1,movingPos:6}]));assert.equal(kd.readKdHistory().length,1);delete global.window;delete global.localStorage;});
test('time snapshot declares civil timezone separately from lunar calendar convention',()=>{const r=kd.castTime('2026-09-24T00:00:00Z');assert.equal(r.metadata.timezone,'Asia/Ho_Chi_Minh');assert.equal(r.metadata.lunarConvention,'Chinese-standard-UTC+8');});
test('tampered coin history values and trigram bits are rejected',()=>{const store=new Map();global.window={};global.localStorage={getItem:k=>store.get(k)||null,setItem:(k,v)=>store.set(k,v)};const e=kd.createKdHistory(kd.castCoins([6,7,8,9,6,9]),'x');e.snapshot.metadata.values='bad';store.set('astrox_kd_history_v1',JSON.stringify([e]));assert.equal(kd.readKdHistory().length,0);delete global.window;delete global.localStorage;});

test('legacy replay preserves purchased cache key',()=>{const e={s1:1,s2:6,s3:6,question:'old',savedAt:1,name:'Trời Nước',movingPos:1};const r=kd.replayKdHistory(e);const {PROMPT_VERSION}=require('../src/lib/config.ts');assert.equal(kd.kdCacheKey(r,'old'),kd.stableHash(JSON.stringify({question:'old',s1:1,s2:6,s3:6,movingPos:r.movingPos,promptVersion:PROMPT_VERSION})));});
