import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {testEnv} from '../admin/test/sqlite.mjs';
import {defaultConfig} from '../admin/config.ts';
import {state,saveDraft,publish} from '../admin/store.mjs';
import {legacySnapshot, runtimeSettings, capabilities} from './config.mjs';
import {sessionCookie,readSession,verifyZaloUser} from './auth.mjs';
import {payosSignature,handlePayosWebhook,handleTopupCreate} from './payments.mjs';

async function fixture(){
 const env=testEnv();
 for(const q of readFileSync(new URL('./test/legacy-schema.sql',import.meta.url),'utf8').split(';').filter(s=>s.trim()))await env.DB.prepare(q).run();
 for(const q of readFileSync(new URL('../../migrations/backend.sql',import.meta.url),'utf8').split(';').filter(s=>s.trim()))await env.DB.prepare(q).run();
 Object.assign(env,{SESSION_SECRET:'test-session-secret',PAYOS_CLIENT_ID:'client',PAYOS_API_KEY:'test-api',PAYOS_CHECKSUM_KEY:'test-checksum',ZALO_APP_ID:'123456',ZALO_APP_SECRET:'test-zalo',ZALO_REDIRECT_URI:'https://api.example.com/auth/zalo/callback'});
 await env.DB.prepare("INSERT INTO app_users(id,display_name,status,created_at,updated_at) VALUES('u1','User','active','2026-01-01','2026-01-01')").run();
 await env.DB.prepare("INSERT INTO zalo_point_accounts VALUES('u1',10,'2026-01-01')").run();
 await env.DB.prepare("INSERT INTO topup_packages VALUES('old',50000,55,'50k',1,1,'2026-01-01')").run();
 return env;
}
async function published(env,change){await state(env);const c=defaultConfig();c.billing.enabled=true;c.integrations.payos={enabled:true,clientId:'client',returnUrl:'https://theastrox.space/hoso',cancelUrl:'https://theastrox.space/hoso',expiryMinutes:30};c.billing.packages=[{id:'new',name:'New',amountVnd:60000,mode:'fixed',fixedPoints:70,bonus:5,enabled:true,featured:false}];change?.(c);await saveDraft(env,'test',c,0);await publish(env,'test',c,1,'test');return c;}
test('imports legacy packages and connection readiness without keys or customer data',async()=>{const env=await fixture(),s=await legacySnapshot(env);assert.equal(s.packages[0].points,55);assert.equal(s.integrations.zalo.appId,'123456');assert.ok(s.inheritedSecrets.includes('payos:apiKey'));assert.ok(!JSON.stringify(s).includes('test-api'));assert.equal(capabilities(env).features.paidAi,false);assert.equal(capabilities(env).features.rewards,false)});
test('published configuration wins over legacy tables and retains env credentials',async()=>{const env=await fixture();await published(env);const s=await runtimeSettings(env);assert.equal(s.packages[0].amount_vnd,60000);assert.equal(s.packages[0].points,75);assert.equal(s.env.PAYOS_API_KEY,'test-api');assert.equal(s.revision,1)});
test('legacy session signature remains valid, expired and missing-secret sessions fail closed',async()=>{const env=await fixture();const cookie=(await sessionCookie(env,'u1')).split(';')[0];assert.equal((await readSession(env,new Request('https://api.example.com',{headers:{cookie}}))).sub,'u1');assert.equal(await readSession({...env,SESSION_SECRET:''},new Request('https://api.example.com',{headers:{cookie}})),null);const expired=(await sessionCookie(env,'u1',Date.now()-31*86400000)).split(';')[0];assert.equal(await readSession(env,new Request('https://api.example.com',{headers:{cookie:expired}})),null)});
test('Zalo identity is obtained from provider and client identity cannot substitute for verification',async()=>{const verified=await verifyZaloUser('test-token',async()=>Response.json({id:'provider-id',name:'Verified'}));assert.equal(verified.id,'provider-id');await assert.rejects(()=>verifyZaloUser('test-token',async()=>Response.json({error:-1})),/zalo_identity_unverified/)});
async function order(env){await env.DB.prepare("INSERT INTO topup_orders_zalo(id,user_id,order_code,amount_vnd,points,status,idempotency_key,created_at) VALUES('o1','u1',12345,50000,55,'pending','order1','2026-01-01')").run();}
async function webhook(env,patch={}){const data={orderCode:12345,amount:50000,code:'00',...patch};const signature=await payosSignature(env.PAYOS_CHECKSUM_KEY,data);return new Request('https://api.example.com/api/webhooks/payos',{method:'POST',body:JSON.stringify({code:'00',success:true,data,signature})});}
test('PayOS webhook credits once and keeps old order points after config changes',async()=>{const env=await fixture();await order(env);await published(env,c=>{c.integrations.payos.enabled=false});assert.equal((await handlePayosWebhook(env,await webhook(env))).status,200);assert.equal((await handlePayosWebhook(env,await webhook(env))).status,200);assert.equal((await env.DB.prepare("SELECT balance FROM zalo_point_accounts WHERE user_id='u1'").first()).balance,65);assert.equal((await env.DB.prepare('SELECT COUNT(*) n FROM zalo_point_ledger').first()).n,1);assert.equal((await env.DB.prepare("SELECT status FROM topup_orders_zalo WHERE id='o1'").first()).status,'paid')});
test('invalid webhook signature or amount never changes balances',async()=>{const env=await fixture();await order(env);const bad=new Request('https://api.example.com/api/webhooks/payos',{method:'POST',body:JSON.stringify({data:{orderCode:12345,amount:50000,code:'00'},signature:'forged'})});assert.equal((await handlePayosWebhook(env,bad)).status,400);await handlePayosWebhook(env,await webhook(env,{amount:1}));assert.equal((await env.DB.prepare("SELECT balance FROM zalo_point_accounts WHERE user_id='u1'").first()).balance,10)});
test('credit failure rolls back ledger and order status, so webhook retry can succeed',async()=>{const env=await fixture();await order(env);await env.DB.prepare("CREATE TRIGGER reject_credit BEFORE UPDATE ON zalo_point_accounts BEGIN SELECT RAISE(ABORT,'test rollback'); END").run();const request=await webhook(env);await assert.rejects(()=>handlePayosWebhook(env,request),/test rollback/);assert.equal((await env.DB.prepare('SELECT COUNT(*) n FROM zalo_point_ledger').first()).n,0);assert.equal((await env.DB.prepare("SELECT status FROM topup_orders_zalo WHERE id='o1'").first()).status,'pending');await env.DB.prepare('DROP TRIGGER reject_credit').run();await handlePayosWebhook(env,await webhook(env));assert.equal((await env.DB.prepare("SELECT balance FROM zalo_point_accounts WHERE user_id='u1'").first()).balance,65);
});
test('new payment uses published package and stores snapshot before upstream',async()=>{const env=await fixture();await published(env);const cookie=(await sessionCookie(env,'u1')).split(';')[0];let sent;
 const response=await handleTopupCreate(env,new Request('https://api.example.com/api/topup/create',{method:'POST',headers:{cookie,origin:'https://theastrox.space'},body:JSON.stringify({amount_vnd:60000})}),async(url,init)=>{sent=JSON.parse(init.body);assert.equal((await env.DB.prepare('SELECT COUNT(*) n FROM backend_order_snapshots').first()).n,1);const data={checkoutUrl:'https://pay.payos.vn/test',paymentLinkId:'link',orderCode:sent.orderCode,amount:60000};return Response.json({code:'00',data,signature:await payosSignature(env.PAYOS_CHECKSUM_KEY,data)})});
 assert.equal(response.status,200);assert.equal((await response.json()).points,75);assert.equal(sent.returnUrl,'https://theastrox.space/hoso');assert.ok(sent.expiredAt);const snap=await env.DB.prepare('SELECT * FROM backend_order_snapshots').first();assert.equal(snap.config_revision,1);
});
test('public routing never exposes internal configuration endpoints',async()=>{const {publicFetch}=await import('./handler.mjs');const env=await fixture();for(const path of ['/internal/admin/capabilities','/internal/admin/bootstrap','/internal/admin/users'])assert.equal((await publicFetch(new Request('https://astrox-internal'+path,{headers:{'x-admin-actor':'fake'}}),env)).status,404)});
test('legacy import retains exact package totals and maps active services',async()=>{const {importLegacyConfig}=await import('../admin/backend.mjs');const env=await fixture();const c=importLegacyConfig(defaultConfig(),await legacySnapshot(env));assert.equal(c.billing.packages[0].fixedPoints,55);assert.equal(c.integrations.payos.enabled,true);assert.equal(c.billing.enabled,true);assert.equal(c.billing.services.find(s=>s.id==='tuvi').status,'free')});
test('promotion reservations prevent concurrent oversubscription before payment',async()=>{const env=await fixture();await published(env,c=>{c.billing.promos=[{id:'once',code:'ONCE',bonus:10,limit:1,perUser:1,enabled:true,expiresAt:''}]});const cookie=(await sessionCookie(env,'u1')).split(';')[0];const req=()=>new Request('https://api.example.com/api/topup/create',{method:'POST',headers:{cookie,origin:'https://theastrox.space'},body:JSON.stringify({amount_vnd:60000,promo_code:'ONCE'})});const upstream=async(url,init)=>{const b=JSON.parse(init.body),data={orderCode:b.orderCode,amount:b.amount,checkoutUrl:'https://pay.payos.vn/test',paymentLinkId:'link'};return Response.json({code:'00',data,signature:await payosSignature(env.PAYOS_CHECKSUM_KEY,data)})};assert.equal((await handleTopupCreate(env,req(),upstream)).status,200);const second=await handleTopupCreate(env,req(),upstream);assert.equal(second.status,400);assert.equal((await second.json()).error,'promo_exhausted')});
test('new orders disabled in Admin do not reach PayOS',async()=>{const env=await fixture();await published(env,c=>{c.billing.enabled=false});const cookie=(await sessionCookie(env,'u1')).split(';')[0];let called=false;const r=await handleTopupCreate(env,new Request('https://api.example.com/api/topup/create',{method:'POST',headers:{cookie,origin:'https://theastrox.space'},body:JSON.stringify({amount_vnd:50000})}),async()=>{called=true;throw Error()});assert.equal(r.status,503);assert.equal(called,false)});
