import test from 'node:test';import assert from 'node:assert/strict';import {testEnv} from '../admin/test/sqlite.mjs';import {accountData} from './user-data.mjs';
const get=()=>new Request('https://api.example.com/api/user-data');const put=(revision,payload)=>new Request('https://api.example.com/api/user-data',{method:'PUT',body:JSON.stringify({expectedRevision:revision,payload})});
async function fixture(){const env=testEnv();await env.DB.prepare('CREATE TABLE user_data(user_id TEXT PRIMARY KEY,payload TEXT NOT NULL,updated_at INTEGER NOT NULL)').run();return env;}
test('new device downloads saved readings; stale or unversioned upload cannot overwrite them',async()=>{const env=await fixture();assert.equal((await accountData(env,put(0,{profile:{name:'An'},aiCache:{saved:'paid reading'}}),'zalo:a')).status,200);const data=await(await accountData(env,get(),'zalo:a')).json();assert.equal(data.aiCache.saved,'paid reading');assert.ok(data._syncRevision>0);assert.equal((await accountData(env,put(0,{}),'zalo:a')).status,409);assert.equal((await accountData(env,put(undefined,{}),'zalo:a')).status,428);assert.equal((await(await accountData(env,get(),'zalo:a')).json()).profile.name,'An');});
test('account namespaces are isolated and concurrent writes have only one winner',async()=>{const env=await fixture();const responses=await Promise.all([accountData(env,put(0,{profile:{name:'A'}}),'zalo:a'),accountData(env,put(0,{profile:{name:'B'}}),'zalo:a')]);assert.deepEqual(responses.map(r=>r.status).sort(),[200,409]);assert.deepEqual(await(await accountData(env,get(),'zalo:b')).json(),{_syncRevision:0});assert.equal((await accountData(env,get(),null)).status,401);});
test('current-revision empty upload cannot erase a saved profile or readings',async()=>{const env=await fixture();await accountData(env,put(0,{profile:{name:'Saved'},aiCache:{saved:{text:'keep',updatedAt:1}},tarotHistory:[{id:'t',savedAt:1}]}),'zalo:a');const initial=await(await accountData(env,get(),'zalo:a')).json();const result=await accountData(env,put(initial._syncRevision,{profile:null,aiCache:{},tarotHistory:[]}),'zalo:a');assert.equal(result.status,200);const saved=await(await accountData(env,get(),'zalo:a')).json();assert.equal(saved.profile.name,'Saved');assert.equal(saved.aiCache.saved.text,'keep');assert.equal(saved.tarotHistory.length,1);});
test('changing a reading preserves its earlier text as history',async()=>{const env=await fixture();await accountData(env,put(0,{aiCache:{saved:{text:'old',updatedAt:1}}}),'zalo:a');const initial=await(await accountData(env,get(),'zalo:a')).json();await accountData(env,put(initial._syncRevision,{aiCache:{saved:{text:'new',updatedAt:2}}}),'zalo:a');const saved=await(await accountData(env,get(),'zalo:a')).json();assert.equal(saved.aiCache.saved.text,'new');assert.ok(Object.values(saved.aiCache).some(x=>x.text==='old'));});
test('database retains five prior versions and unchanged sync does not create extra versions',async()=>{
 const {readFileSync}=await import('node:fs');const env=await fixture();const sql=readFileSync(new URL('../../migrations/user-data-revisions.sql',import.meta.url),'utf8');const at=sql.indexOf('CREATE TRIGGER');await env.DB.prepare(sql.slice(0,at)).run();await env.DB.prepare(sql.slice(at)).run();
 let revision=0;for(let i=0;i<8;i++){const r=await accountData(env,put(revision,{profile:{name:'Version '+i}}),'zalo:a');assert.equal(r.status,200);revision=(await r.json()).revision;}
 const rows=await env.DB.prepare("SELECT payload FROM user_data_revisions WHERE user_id='zalo:a' ORDER BY revision").all();assert.deepEqual(rows.results.map(x=>JSON.parse(x.payload).profile.name),['Version 2','Version 3','Version 4','Version 5','Version 6']);
 const same=await accountData(env,put(revision,{profile:{name:'Version 7'}}),'zalo:a');assert.equal((await same.json()).revision,revision);
});
