import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {testEnv} from '../admin/test/sqlite.mjs';
import {zaloCallback,zaloFinish,readSession} from './auth.mjs';
async function fixture(){const env=testEnv();for(const path of ['services/backend/test/legacy-schema.sql','migrations/backend.sql','migrations/reward-events.sql','migrations/rewards.sql','migrations/zalo-browser.sql']){for(const q of readFileSync(path,'utf8').split(';').filter(x=>x.trim()))await env.DB.prepare(q).run();}return Object.assign(env,{SESSION_SECRET:'test-secret',ZALO_BROWSER_FALLBACK_ENABLED:'true',ZALO_APP_ID:'123',ZALO_APP_SECRET:'secret',APP_ORIGIN:'https://theastrox.space'});}
const settings={zalo:{returnUrl:'https://theastrox.space/'}};
const origin='https://api.theastrox.space';
async function begin(env,code=-501){const state=crypto.randomUUID();await env.DB.prepare('INSERT INTO oauth_states(id,code_verifier,created_at) VALUES(?,?,?)').bind(state,'verifier',new Date().toISOString()).run();return zaloCallback(env,new Request(origin+'/auth/zalo/callback?state='+state+'&code=code',{headers:{cookie:'astrox_oauth='+state}}),settings,async url=>url.includes('oauth.zaloapp')?Response.json({access_token:'test-zalo-token'}):Response.json({error:code}));}
async function pending(env){const r=await begin(env);assert.equal(r.status,302);const cookie=r.headers.get('set-cookie').split(';')[0];const location=r.headers.get('location');const page=await zaloFinish(env,new Request(origin+location,{headers:{cookie}}),settings);assert.equal(page.status,200);const html=await page.text();const config=JSON.parse(html.match(/const config=(.*?);\n/)[1]);return {cookie,config,html,page};}
const finish=(env,p,overrides={})=>zaloFinish(env,new Request(origin+'/auth/zalo/finish',{method:'POST',headers:{origin,cookie:p.cookie,'content-type':'application/json',...overrides.headers},body:JSON.stringify({id:p.config.id,proof:p.config.proof,me:{id:'123456789',name:'Test user'},...overrides.body})}),settings);
test('explicitly enabled browser fallback is cookie-bound, encrypted, one-use and grants normal session',async()=>{const env=await fixture(),p=await pending(env);assert.match(p.page.headers.get('content-security-policy'),/script-src 'nonce-/);assert.doesNotMatch(p.html,/unsafe-inline/);assert.equal(p.page.headers.get('referrer-policy'),'no-referrer');const row=await env.DB.prepare('SELECT * FROM zalo_browser_pending').first();assert.ok(!JSON.stringify(row).includes('test-zalo-token'));const result=await finish(env,p);assert.equal(result.status,200);const cookie=result.headers.get('set-cookie').match(/astrox_session=[^;]+/)[0];assert.ok(await readSession(env,new Request(origin,{headers:{cookie}})));assert.equal((await finish(env,p)).status,400);});
test('missing/wrong cookie cannot read pending token',async()=>{const env=await fixture(),p=await pending(env);for(const cookie of ['', 'astrox_zalo_finish=wrong']){const r=await zaloFinish(env,new Request(origin+'/auth/zalo/finish?id='+p.config.id,{headers:{cookie}}),settings);assert.equal(r.status,400);assert.ok(!(await r.text()).includes('test-zalo-token'));}});
test('cross-origin and incorrect proof cannot consume pending session',async()=>{const env=await fixture(),p=await pending(env);assert.equal((await finish(env,p,{headers:{origin:'https://evil.example'}})).status,403);assert.equal((await finish(env,p,{body:{proof:'wrong'}})).status,400);assert.equal((await finish(env,p)).status,200);});
test('expired pending session and malformed identity are rejected',async()=>{const env=await fixture(),p=await pending(env);assert.equal((await finish(env,p,{body:{me:{id:'<script>'}}})).status,400);await env.DB.prepare('UPDATE zalo_browser_pending SET expires_at=0').run();assert.equal((await finish(env,p)).status,400);});
test('fallback applies only to provider -501 and remains off by default',async()=>{const env=await fixture();assert.equal((await begin(env,-216)).status,502);delete env.ZALO_BROWSER_FALLBACK_ENABLED;assert.equal((await begin(env)).status,502);});
test('browser fallback resumes the existing account and wallet without duplicating users',async()=>{const env=await fixture();await env.DB.prepare("INSERT INTO app_users(id,display_name,status,created_at,updated_at) VALUES('existing','Existing user','active','2026-01-01','2026-01-01')").run();await env.DB.prepare("INSERT INTO zalo_identities(id,user_id,provider,provider_subject,created_at) VALUES('identity','existing','zalo','123456789','2026-01-01')").run();await env.DB.prepare("INSERT INTO zalo_point_accounts(user_id,balance,updated_at) VALUES('existing',77,'2026-01-01')").run();const p=await pending(env),response=await finish(env,p);assert.equal(response.status,200);const cookie=response.headers.get('set-cookie').match(/astrox_session=[^;]+/)[0];assert.equal((await readSession(env,new Request(origin,{headers:{cookie}}))).sub,'existing');assert.equal((await env.DB.prepare('SELECT COUNT(*) AS n FROM app_users').first()).n,1);assert.equal((await env.DB.prepare("SELECT balance FROM zalo_point_accounts WHERE user_id='existing'").first()).balance,77);});
test('parallel submissions consume a pending browser session only once',async()=>{const env=await fixture(),p=await pending(env);const results=await Promise.all([finish(env,p),finish(env,p)]);assert.deepEqual(results.map(r=>r.status).sort(),[200,400]);});
