"use client";
import {useEffect,useState} from 'react';import Link from 'next/link';
type Price={id:string;module:string;name:string;status:string;points:number};type Package={id:string;name:string;amountVnd:number;points:number};
export function PricingContent(){
 const [data,setData]=useState<{services:Price[];packages:Package[];enabled:boolean}|null>(null),[error,setError]=useState(false);
 useEffect(()=>{const c=new AbortController();fetch('/api/site-config',{signal:c.signal}).then(r=>{if(!r.ok)throw Error();return r.json();}).then(d=>{if(!d.config?.billing)throw Error();setData(d.config.billing);}).catch(()=>{if(!c.signal.aborted)setError(true);});return()=>c.abort();},[]);
 if(error)return <p role="alert" className="mt-8">Chưa tải được bảng giá. Vui lòng thử lại sau; chưa có giao dịch nào được tạo.</p>;
 if(!data)return <p role="status" className="mt-8">Đang tải giá hiện hành…</p>;
 return <><div className="mt-8 overflow-hidden rounded-2xl border border-[#d3d9c5]"><table className="w-full text-left text-sm"><thead><tr className="bg-[#edf0e2]"><th className="p-4">Dịch vụ</th><th className="p-4 text-right">Mỗi lượt</th></tr></thead><tbody>{data.services.filter(s=>s.id!==s.module).map(s=><tr key={s.id} className="border-t border-[#e5e6db]"><td className="p-4">{s.name}</td><td className="p-4 text-right">{s.status==='free'?'Miễn phí':s.status==='paid'&&data.enabled?`${s.points} Point`:'Tạm ngưng'}</td></tr>)}</tbody></table></div><h2 className="mt-10 font-display text-2xl">Gói nạp Point</h2><div className="mt-4 grid gap-3 sm:grid-cols-3">{data.packages.map(p=><div key={p.id} className="rounded-2xl border border-[#d3d9c5] p-5"><strong>{p.points} Point</strong><p className="mt-2">{p.amountVnd.toLocaleString('vi-VN')}đ</p></div>)}</div><p className="mt-6 text-sm">Đăng nhập bằng Zalo để nạp Point. <Link className="underline" href="/hoso?section=points">Mở ví Point ↗</Link></p><Link className="mt-4 block text-sm underline" href="/dieukhoan">Điều khoản, hoàn Point và liên hệ hỗ trợ</Link></>;
}
