import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import ts from 'typescript';
function compile(file,require,globals={}){const exports={};new Function('exports','require',...Object.keys(globals),ts.transpileModule(fs.readFileSync(new URL('../src/lib/'+file,import.meta.url),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText)(exports,require,...Object.values(globals));return exports;}
const {mergeCloud}=compile('cloud-merge.ts',()=>{});
test('merge preserves remote profile on new device, offline edits, readings and deletion markers',()=>{
 const remote={profile:{name:'Remote'},aiCache:{a:{text:'new',updatedAt:2}},tarotHistory:[{id:'a',fingerprint:'x',savedAt:1}],tarotDeleted:{x:['a']}};
 const local={profile:null,aiCache:{a:{text:'old',updatedAt:1},b:{text:'other'}},tarotHistory:[{id:'b',fingerprint:'x',savedAt:2}]};
 const merged=mergeCloud(remote,local,local);assert.deepEqual(merged.profile,remote.profile);assert.equal(merged.aiCache.a.text,'new');assert.equal(merged.aiCache.b.text,'other');assert.equal(merged.tarotHistory.length,2);assert.deepEqual(merged.tarotDeleted,{x:['a']});
 assert.deepEqual(mergeCloud(remote,{...local,profile:{name:'Offline'}},local).profile,{name:'Offline'});
});
const flush=()=>new Promise(resolve=>setImmediate(resolve));
function fixture(fetch){let state={profile:null,aiCache:{},chartImageBase64:null,chartImageMime:'image/jpeg',ziweiChart:null,natalChart:null};let dirty;const data=new Map();const storage={getItem:k=>data.get(k)||null,setItem:(k,v)=>data.set(k,v)};const api=compile('cloud-sync.ts',name=>name==='react'?{useSyncExternalStore:(_,get)=>get()}:name==='./cloud-merge'?{mergeCloud}:{getState:()=>state,setState:p=>{state={...state,...p};},onDataDirty:fn=>{dirty=fn;return()=>{dirty=null;};},accountStorageKey:k=>k},{localStorage:storage,fetch,document:{visibilityState:'hidden'},setInterval:()=>1,clearInterval:()=>{},setTimeout:()=>1,clearTimeout:()=>{}});return {ready:()=>api.useCloudProfileReady(),start:()=>api.startCloudSync('/api/user-data',async()=>({})),get:()=>state,edit:profile=>{state={...state,profile};dirty?.();},storage};}
test('failed download never uploads blank local data',async()=>{const methods=[];const f=fixture(async(_,opts)=>{methods.push(opts.method);return new Response(null,{status:503});});const stop=f.start();await flush();stop();assert.deepEqual(methods,['GET']);});
test('stopped sync ignores late download after account switch',async()=>{let resolve;const f=fixture(()=>new Promise(r=>{resolve=r;}));const stop=f.start();await flush();stop();resolve(Response.json({_syncRevision:1,profile:{name:'Private A'}}));await flush();assert.equal(f.get().profile,null);});
test('new device downloads before upload and preserves edits made during request',async()=>{let resolve;const calls=[];const f=fixture(async(_,opts)=>{calls.push(opts);if(opts.method==='GET')return new Promise(r=>{resolve=r;});return Response.json({revision:2});});const stop=f.start();await flush();f.edit({name:'Edited while loading'});resolve(Response.json({_syncRevision:1,profile:{name:'Remote'},aiCache:{saved:'reading'}}));await flush();stop();assert.deepEqual(calls.map(c=>c.method),['GET','PUT']);const sent=JSON.parse(calls[1].body);assert.equal(sent.expectedRevision,1);assert.equal(sent.payload.profile.name,'Edited while loading');assert.equal(sent.payload.aiCache.saved,'reading');assert.ok(f.storage.getItem('astrox_cloud_base'));});

test('profile onboarding waits for successful first download, and resets on account switch',async()=>{let resolve;const f=fixture((_,opts)=>opts.method==='GET'?new Promise(r=>{resolve=r;}):Promise.resolve(Response.json({revision:2})));assert.equal(f.ready(),false);const stop=f.start();await flush();assert.equal(f.ready(),false);resolve(Response.json({_syncRevision:1,profile:{name:'Saved profile'}}));await flush();assert.equal(f.ready(),true);assert.equal(f.get().profile.name,'Saved profile');stop();assert.equal(f.ready(),false);});
test('failed initial download does not permit captive profile onboarding',async()=>{const f=fixture(async()=>new Response(null,{status:503}));const stop=f.start();await flush();assert.equal(f.ready(),false);stop();});
