import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {aiReport as report} from './ai-report.mjs';
const aiReport=(env,params)=>report(env,params,Date.parse('2026-09-25T00:00:00Z'));
function fixture(){const db=new DatabaseSync(':memory:');db.exec('CREATE TABLE admin_ai_requests(id TEXT PRIMARY KEY,service_id TEXT,created_at TEXT,status TEXT,attempts TEXT,duration_ms INTEGER)');let maxRows=0;return {db,env:{DB:{prepare(q){return {bind(...args){return {async all(){const results=db.prepare(q).all(...args);maxRows=Math.max(maxRows,results.length);return {results}},async first(){return db.prepare(q).get(...args)}}}}}}},maxRows:()=>maxRows};}
test('full period and selected service survive more than 5000 newer requests, with exact latency and bounded batches',async()=>{const f=fixture();const insert=f.db.prepare('INSERT INTO admin_ai_requests VALUES(?,?,?,?,?,?)');for(let i=0;i<6001;i++)insert.run(String(i),'tuvi','2026-09-23T20:00:00.000Z','success','[]',i);insert.run('old','tarot','2026-09-23T18:00:00.000Z','replayed','[]',100);
 const all=await aiReport(f.env,new URLSearchParams('from=2026-09-24&to=2026-09-24'));assert.equal(all.summary.requests,6002);assert.equal(all.summary.p95Ms,5700);assert.equal(all.truncated,false);assert.equal(all.summary.daily[0].day,'2026-09-24');assert.ok(f.maxRows()<=500);
 const selected=await aiReport(f.env,new URLSearchParams('from=2026-09-24&to=2026-09-24&service=tarot'));assert.equal(selected.summary.requests,1);assert.equal(selected.summary.replayed,1);assert.equal(selected.summary.averageMs,100);assert.ok(selected.options.services.includes('tarot'));f.db.close();});
test('provider and model must match the same attempt; VN boundaries are exclusive',async()=>{const f=fixture(),put=f.db.prepare('INSERT INTO admin_ai_requests VALUES(?,?,?,?,?,?)');const attempts=JSON.stringify([{providerId:'a:route',model:'one',outcome:'success'},{providerId:'b',model:'two',outcome:'success'}]);for(const [id,date] of [['before','2026-09-23T16:59:59.999Z'],['start','2026-09-23T17:00:00.000Z'],['end','2026-09-24T17:00:00.000Z']])put.run(id,'tuvi',date,'success',attempts,100);const params=new URLSearchParams('from=2026-09-24&to=2026-09-24&provider=a&model=one');assert.equal((await aiReport(f.env,params)).summary.requests,1);params.set('model','two');assert.equal((await aiReport(f.env,params)).summary.requests,0);await assert.rejects(aiReport(f.env,new URLSearchParams('from=2026-02-30')),{status:422});f.db.close();});
test('malformed historical attempts do not break reports or pretend to match a provider',async()=>{const f=fixture(),put=f.db.prepare('INSERT INTO admin_ai_requests VALUES(?,?,?,?,?,?)');for(const [i,value] of ['broken','null','{}','["scalar",null,42]', '[{"providerId":"a","outcome":"success"}]'].entries())put.run(String(i),'tuvi','2026-09-23T20:00:00.000Z','success',value,1);assert.equal((await aiReport(f.env,new URLSearchParams('from=2026-09-24&to=2026-09-24&provider=a'))).summary.requests,1);f.db.close();});
