/** English display names keyed by stable catalog ids; computation and ownership use ids. */
export const SERVICE_NAMES_EN: Record<string, string> = {
  'tarot--spreads': 'Tarot spreads',
  'batu--readings': 'Ba Zi readings',
  'numerology--readings': 'Numerology readings',
  'tuvi--period': 'Fortune cycles',
  'zodiac--period': 'Forecasts',
  tuvi: 'Zi Wei',
  batu: 'Ba Zi',
  zodiac: 'Astrology',
  numerology: 'Numerology',
  tarot: 'Tarot',
  kinhdich: 'I Ching',
  compat: 'Compatibility',
  palm: 'Palm reading',
  'lunar-calendar': 'Lunar calendar',
  'kinhdich--interpretation': 'I Ching interpretation',
  'compat--pair': 'Zodiac compatibility',
  'compat--tuvi-pair': 'Zi Wei pair reading',
  'compat--batu-pair': 'Ba Zi pair reading',
  'numerology--life-path': 'Life path',
  'numerology--destiny': 'Destiny',
  'numerology--inner-self': 'Inner self',
  'numerology--birth-grid': 'Birth grid',
  'numerology--cycles': 'Life cycles',
  'numerology--personal-year': 'Personal year',
  'tuvi--tim-hieu-ban-than': 'Understanding yourself',
  'tuvi--su-nghiep-tai-loc': 'Career & wealth',
  'tuvi--van-trinh-su-nghiep': 'Career trajectory',
  'tuvi--hieu-ban-doi': 'Understanding your partner',
  'tuvi--tinh-duyen-hon-nhan': 'Love & marriage',
  'tuvi--vi-sao-toi-la-toi': 'Why I am me',
  'tuvi--hoc-hanh-thi-cu': 'Study & exams 2026',
  'tuvi--doi-cong-viec-2026': 'Change jobs in 2026?',
  'tuvi--tieu-van-2026': '2026 annual fortune',
  'tuvi--cau-hoi-xuat-ngoai': 'Going abroad',
  'tuvi--cau-hoi-tien-tai': 'Money questions',
  'tuvi--cau-hoi-su-nghiep': 'Career questions',
  'tuvi--xu-huong-dai-van': 'Decade outlook',
  'tuvi--tim-hieu-ban-than--tinh-cach': 'Character & tendencies',
  'tuvi--tim-hieu-ban-than--thu-thach': 'Challenges & growth path',
  'tuvi--tim-hieu-ban-than--yeu-to-tac-dong': 'Life-shaping factors',
  'tuvi--tim-hieu-ban-than--no-nghiep': 'Karmic lessons',
  'tuvi--su-nghiep-tai-loc--tong-quan': 'Wealth & career overview',
  'tuvi--su-nghiep-tai-loc--con-nguoi-cong-viec': 'You at work',
  'tuvi--su-nghiep-tai-loc--nganh-nghe': 'Fitting industries',
  'tuvi--su-nghiep-tai-loc--loi-khuyen-tc': 'Career & finance advice',
  'tuvi--van-trinh-su-nghiep--van-trinh-cong-danh': 'Career trajectory',
  'tuvi--hieu-ban-doi--hieu-ban-doi-sub': 'Your potential partner',
  'tuvi--hieu-ban-doi--tac-dong-nguoi-ngoai': 'Outside influences',
  'tuvi--hieu-ban-doi--hai-nguoi': 'Two people — relationship dynamics',
  'tuvi--tinh-duyen-hon-nhan--ban-trong-tinh-yeu': 'You in love',
  'tuvi--tinh-duyen-hon-nhan--ai-thu-hut': 'Who is drawn to you',
  'tuvi--tinh-duyen-hon-nhan--kieu-nguoi-gap': 'Partner types you meet',
  'tuvi--tinh-duyen-hon-nhan--ca-tinh-phu-hop': 'Complementary personalities',
  'tuvi--tinh-duyen-hon-nhan--tong-quan-ban-doi': 'Partner overview',
  'tuvi--tinh-duyen-hon-nhan--nhan-dinh-hon-nhan': 'Marriage outlook',
  'tuvi--tinh-duyen-hon-nhan--tinh-cach-con-cai': "Children's character",
  'tuvi--vi-sao-toi-la-toi--su-menh': 'Why I am me',
  'tuvi--hoc-hanh-thi-cu--hoc-hanh-2026': 'Study & exams 2026',
  'tuvi--doi-cong-viec-2026--doi-viec-2026': 'Change jobs in 2026?',
  'tuvi--tieu-van-2026--tong-quan-2026': '2026 overview',
  'tuvi--tieu-van-2026--sunghiep-2026': 'Career 2026',
  'tuvi--tieu-van-2026--tienbac-2026': 'Money 2026',
  'tuvi--tieu-van-2026--tinhcam-2026': 'Love 2026',
  'tuvi--tieu-van-2026--vanhan-2026': 'Watch-outs 2026',
  'tuvi--cau-hoi-xuat-ngoai--danh-gia-co-hoi': 'Assessing opportunities abroad',
  'tuvi--cau-hoi-xuat-ngoai--co-nen-di-xa': 'Should you go far?',
  'tuvi--cau-hoi-xuat-ngoai--nam-co-loi': 'Favorable years for relocation',
  'tuvi--cau-hoi-tien-tai--tiem-nang-giau': 'Wealth potential',
  'tuvi--cau-hoi-tien-tai--hop-lam-chu': 'Are you built to be your own boss?',
  'tuvi--cau-hoi-tien-tai--co-thua-huong': 'Inheritance outlook',
  'tuvi--cau-hoi-tien-tai--hop-bds': 'Fit with real estate',
  'tuvi--cau-hoi-tien-tai--xu-huong-nha': 'Home & assets',
  'tuvi--cau-hoi-su-nghiep--moi-truong-phu-hop': 'Best-fit environment',
  'tuvi--cau-hoi-su-nghiep--hop-to-chuc': 'Traditional vs. startup fit',
  'tuvi--cau-hoi-su-nghiep--don-bay': 'Career levers',
  'tuvi--cau-hoi-su-nghiep--nen-hoc-cao': 'Should you study further?',
  'tuvi--xu-huong-dai-van--dien-bien-40nam': 'The arc of 40 years',
  'tuvi--xu-huong-dai-van--thien-thoi-dia-loi': 'Timing & place advantage',
  'tuvi--xu-huong-dai-van--bieu-do-10nam': 'The next 10 years, year by year',
  'tuvi--period--today': 'Today',
  'zodiac--tong-quan-la-so': 'Chart overview',
  'zodiac--big-3': 'The Big Three',
  'zodiac--hanh-tinh': 'Planets',
  'zodiac--12-nha': 'The 12 houses',
  'zodiac--goc-chieu': 'Aspects',
  'zodiac--tinh-cach-cung': 'Sign character',
  'zodiac--tinh-yeu-cung': 'Love & relationships',
  'zodiac--su-nghiep-cung': 'Work & money',
  'zodiac--period--today': 'Today',
  'tuvi--period--week': 'This week',
  'zodiac--period--week': 'This week',
  'tuvi--period--month': 'This month',
  'zodiac--period--month': 'This month',
  'zodiac--tong-quan-la-so--bo-ba-loi': 'The Big Three',
  'zodiac--tinh-yeu-cung--phong-cach-yeu': 'Love style',
  'zodiac--su-nghiep-cung--huong-su-nghiep': 'Career direction',
  'batu--tinh-cach': 'Character',
  'batu--su-nghiep-tien-tai': 'Career & wealth',
  'batu--tinh-duyen': 'Love',
  'batu--suc-khoe': 'Well-being',
  'tarot--one': 'Single card',
  'tarot--three--ppf': 'Past – Present – Future',
  'tarot--three--sao': 'Situation – Action – Outcome',
  'tarot--three--soa': 'Self – Obstacle – Advice',
  'tarot--cross5': 'Simple Cross',
  'tarot--relationship5': 'Love & Relationships',
  'tarot--celtic10': 'Celtic Cross',
  'zodiac--tong-quan-la-so--diem-noi-bat': 'Chart highlights',
  'zodiac--big-3--mat-troi': 'Sun',
  'zodiac--big-3--mat-trang': 'Moon',
  'zodiac--big-3--cung-moc': 'Ascendant',
  'zodiac--big-3--ket-hop': 'How they blend',
  'zodiac--hanh-tinh--hanh-tinh-ca-nhan': 'Personal planets',
  'zodiac--hanh-tinh--hanh-tinh-xa-xi': 'Social & outer planets',
  'zodiac--12-nha--nhac-trung-tam': 'Angular houses',
  'zodiac--12-nha--nha-khac': 'Other houses',
  'zodiac--goc-chieu--goc-thuan-loi': 'Flowing aspects',
  'zodiac--goc-chieu--goc-thach-thuc': 'Tense aspects',
  'zodiac--tinh-cach-cung--dac-diem-cot-loi': 'Core traits',
  'zodiac--tinh-cach-cung--diem-manh-yeu': 'Strengths & watch-outs',
  'zodiac--tinh-yeu-cung--nhu-cau-cam-xuc': 'Emotional needs',
  'zodiac--su-nghiep-cung--tai-chinh': 'Money',
};
export const englishServiceName = (id: string, fallback = 'AstroX reading') => SERVICE_NAMES_EN[id] ?? fallback;
