import {defaultConfig} from './config.ts';
import {decrypt,encrypt} from './crypto.mjs';
export const sql=(env,q,...args)=>env.DB.prepare(q).bind(...args);
export async function state(env){await sql(env,'INSERT OR IGNORE INTO admin_state(id,draft,revision) VALUES(1,?,0)',JSON.stringify(defaultConfig())).run();return sql(env,'SELECT * FROM admin_state WHERE id=1').first();}
export async function readPublished(env){if(!env.DB)return null;const exists=await sql(env,"SELECT name FROM sqlite_master WHERE type='table' AND name='admin_state'").first();if(!exists)return null;const r=await sql(env,'SELECT v.id,v.config FROM admin_state s JOIN admin_versions v ON s.published_id=v.id WHERE s.id=1').first();return r?{config:JSON.parse(r.config),revision:r.id}:null;}
export async function readSecret(env,ref){const r=await sql(env,'SELECT ciphertext FROM admin_secrets WHERE ref=?',ref).first();return r?decrypt(env,ref,r.ciphertext):null;}
export function auditStatement(env,actor,action,target,detail={}){return sql(env,'INSERT INTO admin_audit(actor,action,target,created_at,detail) VALUES(?,?,?,?,?)',actor,action,target,new Date().toISOString(),JSON.stringify(detail));}
export async function recordAudit(env,actor,action,target,detail={}){return auditStatement(env,actor,action,target,detail).run();}
export async function saveSecret(env,actor,ref,value){const encrypted=await encrypt(env,ref,value);await env.DB.batch([sql(env,'INSERT INTO admin_secrets(ref,ciphertext,updated_at) VALUES(?,?,?) ON CONFLICT(ref) DO UPDATE SET ciphertext=excluded.ciphertext,updated_at=excluded.updated_at',ref,encrypted,new Date().toISOString()),auditStatement(env,actor,'secret.update',ref)]);}
// The conditional write and conditional audit run in one D1 transaction.
export async function saveDraft(env,actor,config,revision){const out=await env.DB.batch([sql(env,'UPDATE admin_state SET draft=?, revision=revision+1 WHERE id=1 AND revision=?',JSON.stringify(config),revision),sql(env,"INSERT INTO admin_audit(actor,action,target,created_at,detail) SELECT ?,'config.save','draft',?,'{}' WHERE changes()=1",actor,new Date().toISOString())]);return out[0].meta.changes===1;}
export async function publish(env,actor,config,revision,note){const now=new Date().toISOString();const out=await env.DB.batch([sql(env,'INSERT INTO admin_versions(config,created_at,actor,note) SELECT ?,?,?,? FROM admin_state WHERE id=1 AND revision=?',JSON.stringify(config),now,actor,note,revision),sql(env,'UPDATE admin_state SET draft=?, revision=revision+1,published_id=(SELECT MAX(id) FROM admin_versions) WHERE id=1 AND revision=? AND changes()=1',JSON.stringify(config),revision),sql(env,"INSERT INTO admin_audit(actor,action,target,created_at,detail) SELECT ?,'config.publish',CAST(published_id AS TEXT),?,? FROM admin_state WHERE id=1 AND changes()=1",actor,now,JSON.stringify({note}))]);return out[0].meta.changes===1;}
